// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"bytedance_douyin/biz/handler"
	"bytedance_douyin/biz/middleware"
	"github.com/cloudwego/hertz/pkg/app/server"

)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	r.Static("/static","./")

	r.POST("/douyin/user/register/",append(middleware.Password(),handler.Register)...)
	r.POST("/douyin/user/login/",append(middleware.Password(),handler.Login)...)

	r.GET("/douyin/feed/",handler.Feed)

	h := r.Group("/douyin")
	h.Use(middleware.Token())
	h.GET("/user/",handler.UserInfo)
	h.POST("/publish/action/",handler.PublishVideo)
	h.GET("/publish/list/",handler.PublishList)
	h.POST("/favorite/action/",handler.FavoriteAction)
	h.GET("/favorite/list/",handler.FavoriteList)
	h.POST("/comment/action/",handler.CommentAction)
	h.GET("/comment/list/",handler.CommentList)
	h.POST("/relation/action/",handler.FollowAction)
}
