// Code generated by hertz generator.

package main

import (
	"bytedance_douyin/biz/config"
	"bytedance_douyin/biz/redis"
	"bytedance_douyin/biz/router"
	_server1 "bytedance_douyin/biz/server"
	"bytedance_douyin/biz/utils"
	"fmt"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/spf13/viper"
)

func init() {
	utils.InitLog()
	config.SetConfig()
	config.InitDB()
	redis.InitRDB()

}

func main() {
	h := server.Default()
	go _server1.IsRdbToDb()
	//register(h)
	router.GeneratedRegister(h)
	fmt.Println(viper.GetString("thisServer.host"))
	h.Spin()

}
