#数据库
#server:
#  post: 8888
datasource:
  driverName: mysql
  host:  127.0.0.1 # 端口地址
  port: 3306 # 端口号
  database: douyin # 数据库名称
  username: root # 账号
  password: admin # 密码
  charset: utf8


redis:
  host: 127.0.0.1
  port: 6379
  db: 0
  password: ""
  pool_size: 100



#this server
thisServer:
  host: 192.168.19.1 # 端口地址
  port: 8888 # 端口号


#ffmpeg
ffmpeg:
  path: D:\0tool\ffmpeg-2023-02-16-git-aeceefa622-essentials_build\bin\ffmpeg.exe



